# Generated by Django 4.2.9 on 2024-01-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userprofile_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='expertise',
            field=models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('History', 'History'), ('Geography', 'Geography'), ('Economics', 'Economics'), ('Computer Science', 'Computer Science')], max_length=20),
        ),
    ]
